name: Build & Deploy

on:
  push:
    branches: [JavixBackend_Master]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Node JS app
          uses: appleboy/ssh-action@v0.1.2     
          with:
            host: ${{secrets.SSH_HOST}} 
            passphrase: ${{secrets.SSH_PASSPHRASE}}
            key:  ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}

            script: |
              cd /mnt/volume_blr1_01/javix/Javix-BackEnd-Cicd
              sh deploy.sh
              echo `Deployment Successfult to Digital Ocean`
